"""add analysis job error

Revision ID: 762df9d0abc6
Revises: 3214d7e50800
Create Date: 2026-10-03 13:20:28.679275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762df9d0abc6'
down_revision: Union[str, Sequence[str], None] = '3214d7e50800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'error_message')
    # ### end Alembic commands ###
